### ISSUE TITLE
Packaging via SetupTools

### ISSUE THREAD

**Issue by ghost** [sparshg/py-games#24]
Should we package the project via SetupTools?

https://packaging.python.org/guides/distributing-packages-using-setuptools/

I'll submit a pull request once you say yes.
And also, couldn't fix the bugs in #23, I might just rewrite the code.

**Comment by sparshg** [comment]
i dont think we should convert this to package yet, it's just few small separate games..
Also, my exams finally got over this week, it got postponed so much but it's now done lol
