### ISSUE TITLE
Add a contributor list to README

### ISSUE THREAD

**Issue by sparshg** [sparshg/py-games#29]
Add a section which shows all the contributors with their (small size) profile icon

**Comment by PeritusDeveloper** [comment]
Will you add the hacktoberfest-accepted tag @sparshg

**Comment by sparshg** [comment]
The repo is already marked, so that should not be needed.
(If it doesn't show as accepted in 20 minutes then you can ask me to put the label though)

**Comment by sparshg** [comment]
The contributor list isn't auto-updating as mentioned in #34. @PeritusDeveloper will you like to look into this?
