### ISSUE TITLE
Add collisions to gravity game

### ISSUE THREAD

**Issue by loneneuron** [sparshg/py-games#78]
Hey, Sparsh! Long time no see!
It's me, loneneuron (or MTM828). You see, I've been inactive on Element becautse I deleted my GitHub a while ago, and my GitHub was my authentication method on Element, so I couldn't access my account anymore. I hope my inactivity hasn't bothered you in any way.
So, how's it going? I'd love to know what you've been doing lately. How're you doing in college, did you write a compiler yet? Did you have fun[1] with words, pointers, instructions and assembly?

I thought the best thing I'd do after the inactivity would be to work on this project again, to give it a spark of life again. The gravity game (more like a 2D gravity simulation) could use perfectly perectly elastic rigid body collisions, like the one here: https://isaacphysics.org/concepts/cp_collisions?stage=all
My Python is a bit rusty, but I think I should have no problems working on it.

And again, sorry for the inactivity, I've been locked out of my Matrix account. We can chat again via email and Telegram if you want. And, erm... can I get promoted to a collaboratir again?

[1]: By "fun", I mean get tortured lol.

**Comment by sparshg** [comment]
Heey, why did you delete your Github? Anyways I have messaged you on telegram, college has been going good and we will be writing that compiler this semester. I have been working on some Rust projects if you see my repos, its been pretty fun. I have invitied you as collabotor. I am not really active on this repo, the hacktoberfest thing made this a bit spammy imo. Are you working on any low level project?

**Comment by loneneuron** [comment]
Yeah, I can see what you mean by spammy.
I'll work on the collisions soon just to see how it'd act like.
I've been working on my 3D renderer, I've managed to effectively wrap OpenGL into a sligntly more high level library, but it's still at the beginning stage rn.
But no, it doesn't get more low level than malloc lol. But I've always wanted to dive into this sort of thing.

Anyway, I'll continue on Telegram.

**Comment by ghost** [comment]
Implemented in commit [95c314e](https://github.com/sparshg/py-games/commit/95c314eeea7827b64510d8bc2089d0771f0e0b9a).
